#ifndef WEBSOCKETPP_TRANSPORT_BARE_SECURITY_NONE_HPP
#define WEBSOCKETPP_TRANSPORT_BARE_SECURITY_NONE_HPP

// TODO what to put in here? asio has it

#endif // WEBSOCKETPP_TRANSPORT_BARE_SECURITY_NONE_HPP